version: '3.4'

services:
  web:
    build: ./docker/php
    container_name: "${APP_NAME}_web"
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: "${APP_NAME}_nginx"
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
